-- 코드를 작성해주세요
SELECT ITEM_INFO.ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO JOIN ITEM_TREE
ON ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
WHERE ITEM_INFO.ITEM_ID NOT IN (
SELECT PARENT_ITEM_ID
FROM ITEM_TREE
WHERE PARENT_ITEM_ID IS NOT NULL
GROUP BY PARENT_ITEM_ID
)
ORDER BY ITEM_ID DESC