-- 코드를 입력하세요
SELECT PRODUCT_CODE,(PRICE*OS.AMOUNT) SALES
FROM PRODUCT JOIN (
    SELECT PRODUCT_ID,SUM(SALES_AMOUNT) AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) OS
ON PRODUCT.PRODUCT_ID = OS.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE