-- 코드를 입력하세요
SELECT CAR.CAR_ID,CAR.CAR_TYPE,
ROUND(DAILY_FEE * 30 *((100-DISCOUNT_RATE)/100)) AS FEE  
FROM CAR_RENTAL_COMPANY_CAR AS CAR JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
ON CAR.CAR_TYPE = PLAN.CAR_TYPE
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY ON CAR.CAR_ID = HISTORY.CAR_ID
WHERE CAR.CAR_TYPE IN ('세단','SUV') 
AND CAR.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-11-30'
) AND PLAN.DURATION_TYPE = '30일 이상'
GROUP BY CAR_ID
HAVING FEE>=500000 AND FEE<2000000
ORDER BY FEE DESC,CAR_TYPE ,CAR_ID DESC