-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH,
    COUNT(DISTINCT ONLINE_SALE.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT ONLINE_SALE.USER_ID) / (SELECT COUNT(DISTINCT USER_ID)
                                                 FROM USER_INFO 
                                                 WHERE YEAR(JOINED)= 2021),1)
                                                 AS PUCHASED_RATIO
FROM USER_INFO INNER JOIN ONLINE_SALE
ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID AND YEAR(JOINED) = 2021
GROUP BY YEAR,MONTH
ORDER BY YEAR,MONTH