-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J
ON FIRST_HALF.FLAVOR = J.FLAVOR
ORDER BY (FIRST_HALF.TOTAL_ORDER+J.TOTAL_ORDER) DESC
LIMIT 3