-- 코드를 입력하세요
SELECT USER_ID,NICKNAME,SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD JOIN USED_GOODS_USER
ON USED_GOODS_USER.USER_ID = USED_GOODS_BOARD.WRITER_ID
WHERE USED_GOODS_BOARD.STATUS='DONE'
GROUP BY USED_GOODS_BOARD.WRITER_ID
HAVING TOTAL_SALES >= 700000 
ORDER BY TOTAL_SALES